#!/bin/bash
example_script="$1"
name="$(basename "$example_script" .jl)"

cat <<EOF
# Example: \`$name\`

![Demo for $name]($name.png "Demo for $name")

Use [\`LyapunovExponents.$name\`](@ref) to generate a
[\`LyapunovExponents.LEDemo\`](@ref) (which wraps
[\`LEProblem\`](@ref)) and solve it.

EOF
echo '```julia'
cat "$example_script"
echo '```'
