#!/bin/bash
example_script="$1"
name="$(basename "$example_script" .jl)"

cat <<EOF
# Example: [\`LyapunovExponents.$name\`](@ref)

![Demo for $name]($name.png "Demo for $name")

EOF
echo '```julia'
cat "$example_script"
echo '```'
